### ISSUE TITLE
Use scala-steward?

### ISSUE THREAD

**Issue by takayahilton** [chronoscala/chronoscala#77]
**Description**
>Scala Steward is a bot that helps you keeping library dependencies and sbt plugins up-to-date.

https://github.com/fthomas/scala-steward#scala-steward

All you have to do is edit this [repos](https://github.com/scala-steward-org/repos/edit/master/repos-github.md) and send PR.

**Comment by takayahilton** [comment]
@sh0hei @lagenorhynque 
could you send PR to [repos](https://github.com/scala-steward-org/repos/edit/master/repos-github.md)?

**Comment by ocadaruma** [comment]
@takayahilton Sounds cool.
By the way have you ever compared to another dependency-checking solution like [renovate](https://docs.renovatebot.com/modules/manager/sbt/)?
